kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "prometheusrule-validating-webhook.name" . }}
  annotations:
    openshift.io/description: ClusterRoleBinding for {{ include "prometheusrule-validating-webhook.name" . }} role
subjects:
- kind: ServiceAccount
  name: {{ include "prometheusrule-validating-webhook.name" . }}
  namespace: {{ include "prometheusrule-validating-webhook.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "prometheusrule-validating-webhook.name" . }}
  apiGroup: rbac.authorization.k8s.io
