kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "prometheusrule-validating-webhook.name" . }}
  annotations:
    openshift.io/description: Role for {{ include "prometheusrule-validating-webhook.name" . }}
rules:
 - apiGroups: [""]
   resources: ["namespaces"]
   verbs: ["get", "list", "watch", "update"]
