apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prometheusrule-validating-webhook.fullname" . }}
  labels:
    {{- include "prometheusrule-validating-webhook.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "prometheusrule-validating-webhook.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "prometheusrule-validating-webhook.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "prometheusrule-validating-webhook.name" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /usr/local/bin/webhook
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: 9443
          volumeMounts:
          # default path if manager.Options.CertDir is not overriden
          # /tmp/k8s-webhook-server/serving-certs/tls.{key,crt} must exist.
          - mountPath: /tmp/k8s-webhook-server/serving-certs
            name: serving-cert
      volumes:
        - name: serving-cert
          secret:
            defaultMode: 420
            secretName: {{ include "prometheusrule-validating-webhook.name" . }}-serving-cert
        {{- with .Values.nodeSelector }}
        nodeSelector:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.affinity }}
        affinity:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.tolerations }}
        tolerations:
          {{- toYaml . | nindent 8 }}
        {{- end }}
