
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: ${WEBHOOK_NAME}-serving-cert
  labels:
    webhook: ${WEBHOOK_NAME}
  name: webhook-service
  namespace: system
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    webhook: ${WEBHOOK_NAME}
